adjust linting similar to cc-utils

diff --git a/.ci/lint b/.ci/lint
--- a/.ci/lint
+++ b/.ci/lint
@@ -3,47 +3,53 @@ set -eu
 
 # usage: $1: <src-dir>
 
-src_dir="${1:-"$(dirname "${BASH_SOURCE[0]}")/.."}"
+src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"
 
-error=0
+linters_with_findings=()
 
-export PYTHONPATH="${src_dir}:${PYTHONPATH-""}"
+if ! which ruff &>/dev/null; then
+    pip3 install --break-system-packages ruff >/dev/null
+fi
 
-(
-    pushd "${src_dir}"
-    echo "using pylama cfg at ${src_dir}/pylama.ini"
-    set -x
+echo 'running ruff check'
+if ruff check "${src_dir}"; then
+    echo 'ruff check succeeded'
+else
+    echo 'ruff check yielded findings (see above)'
+    linters_with_findings+=('ruff-check')
+fi
 
-    echo 'running pylama for all modules (errors only)'
-    if pylama -iW,R,C  -lpylint --options "${src_dir}/pylama.ini" "${src_dir}"; then
-        echo 'pylama succeeded'
-    else
-        ((error|=1))
-    fi
+echo 'running ruff format --check'
+if ruff format --check "${src_dir}"; then
+    echo 'ruff format succeeded'
+else
+    echo 'ruff format yielded findings (see above)'
+    linters_with_findings+=('ruff-format')
+fi
 
-    echo 'running flake8 for all python modules'
-    if ".ci/lint-flake8"; then
-        echo 'pyflake8 succeeded'
-    else
-        ((error|=1))
-    fi
+if ! which bandit &>/dev/null; then
+    pip3 install --break-system-packages bandit >/dev/null
+fi
 
-    echo 'running bandit (sast-linter) for all modules'
-    if bandit \
-        --configfile "${src_dir}/pyproject.toml" \
-        --recursive \
-        "${src_dir}" ${bandit_extra_args:-}; then
-        echo "bandit succeeded"
-    else
-        ((error|=1))
-    fi
+echo "running bandit (sast-linter) - extra-args: ${bandit_extra_args:-}"
+if bandit \
+    --configfile "${src_dir}/pyproject.toml" \
+    --recursive \
+    "${src_dir}" ${bandit_extra_args:-}; then
+    echo "bandit exited without error"
+else
+    linters_with_findings+=('bandit')
+fi
 
-    if [ $error -eq 0 ]; then
-        exit 0
-    elif [ $error -gt 0 ]; then
-        exit 1
-    fi
-    popd
-)
+if [ ${#linters_with_findings[@]} == 0 ]; then
+    echo "all linters exited without findings"
+    exit 0
+else
+    echo "Error: the following linters yielded findings"
+    echo ""
+    for l in "${linters_with_findings[@]}"; do
+        echo " - ${l}"
+    done
 
-exit $?
+    exit 1
+fi
